name: Create Tag for JS Package Version Bump

on:
  push:
    branches:
      - trunk
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag-exists: ${{ steps.check-tag.outputs.tag-exists }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract version from package.json
        id: get-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "Extracted version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
      - name: Check if tag exists
        id: check-tag
        run: |
          if git tag | grep -q "${{ steps.get-version.outputs.version }}"; then
            echo "Tag exists"
            echo "tag-exists=1" >> "$GITHUB_OUTPUT"
          else
            echo "Tag does not exist"
            echo "tag-exists=0" >> "$GITHUB_OUTPUT"
          fi

  create-tag-and-release:
    needs: check-version
    if: needs.check-version.outputs.tag-exists == '0'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag v${{ needs.check-version.outputs.version }}
          git push origin v${{ needs.check-version.outputs.version }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Draft a new release with autogenerated notes
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create v${{ needs.check-version.outputs.version }} --title "Release v${{ needs.check-version.outputs.version }}" --generate-notes --draft
