name: npm-publish

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nodever: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodever }}
      - run: yarn install
      - run: yarn build
      - run: |
          yarn test -t 'cloud'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          RELAY_KEY: ${{ secrets.RELAY_KEY }}
          RELAY_SECRET: ${{ secrets.RELAY_SECRET }}
          RELAY_URL: ${{ secrets.RELAY_URL }}

  publish-npm:
    needs: build
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: node scripts/update-version.js # ensure the version in version.ts is updated
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}