name: test

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install requirements
        run: |
          yarn install
          yarn build
      - name: Running tests
        run: |
          yarn test "3439|6806e8faf10643e2bde903920bbcb1ff"
