name: test

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*

jobs:
  test-cloud:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nodever: [18, 20]
    name: Test with spice.ai cloud on ${{ matrix.os }} Node.js ${{ matrix.nodever }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodever }}
      - name: Running tests
        run: |
          make TEST_SUITE=cloud test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          RELAY_KEY: ${{ secrets.RELAY_KEY }}
          RELAY_SECRET: ${{ secrets.RELAY_SECRET }}
          RELAY_URL: ${{ secrets.RELAY_URL }}

  test-local-spice:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nodever: [18, 20]
    name: Test with local spice runtime on ${{ matrix.os }} Node.js ${{ matrix.nodever }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodever }}

      - name: install Spice (https://install.spiceai.org)
        run: |
          curl https://install.spiceai.org | /bin/bash
          echo "$HOME/.spice/bin" >> $GITHUB_PATH

      - name: Check spice version
        run: spice version

      - name: Running tests
        run: |
          make TEST_SUITE=local test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          RELAY_KEY: ${{ secrets.RELAY_KEY }}
          RELAY_SECRET: ${{ secrets.RELAY_SECRET }}
          RELAY_URL: ${{ secrets.RELAY_URL }}